// use aiken/crypto.{VerificationKeyHash}
// use cardano/address.{Credential, Script}
// use cardano/assets.{AssetName, PolicyId}

// pub const owner: VerificationKeyHash = #"e47502b84a37b65a375e7a1eff4f8e7adea35f773ef716123fa58b54"

// pub const nft_policy_id: PolicyId =
//   #"00000000000000000000000000000000000000000000000000000000"

// pub const nft_asset_name: AssetName = #"4e4654"

// pub const vault: Credential = Script(#"55c8d02b7a3ba6fe100fed4faf0b4f23cfeac2beb5b4888fed3a5c66")
